plugins {
    id("com.android.dynamic-feature")
    id("kotlin-android")
}

android {
    compileSdk 35

    defaultConfig {
        minSdk 26
    }
    namespace 'me.khol.dynamic'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation project(':app')

    implementation libs.androidx.appcompat
    implementation libs.androidx.core
}
