[versions]
compile-sdk = "36"
min-sdk = "26"
target-sdk = "35"

kotlin = "1.8.21"
android = "8.8.0"

androidx-appcompat = "1.7.1"
androidx-core = "1.17.0"
feature-delivery = "2.1.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
feature-delivery = { module = "com.google.android.play:feature-delivery-ktx", version.ref = "feature-delivery" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
