plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    compileSdk libs.versions.compile.sdk.get().toInteger()

    defaultConfig {
        applicationId "me.khol.dynamicupdates"
        minSdk libs.versions.min.sdk.get().toInteger()
        targetSdk libs.versions.target.sdk.get().toInteger()
        versionCode 14
        versionName "1.1.4"
    }

    dynamicFeatures = [":dynamic"]
    namespace 'me.khol.dynamicupdates'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation project(":static")
    implementation project(":static2")

    implementation libs.androidx.appcompat
    implementation libs.androidx.core
    implementation libs.feature.delivery
}
